### ISSUE TITLE
Aggregate all tasks metrics in every stage  

### ISSUE THREAD

**Issue by Aalnafessah** [LucaCanali/Miscellaneous#1]
Hi

Thanks for your help in advance. I have read your notes in ( https://github.com/LucaCanali/Miscellaneous/blob/master/Spark_Notes/Spark_EventLog.md ) 
I want to aggregate all task metrics in every stage. For example, to sum all the tasks metrics (eg: Disk Bytes Spilled,Executor CPU Time,Executor Deserialize CPU Time,and Executor Deserialize Time )  

How can i do that using the spark logs?

**Comment by LucaCanali** [comment]
That note shows how to read metrics Spark task metrics using Spark DataFrame API. Then you can use Spark DataFrame and/or SQL to compute aggregates.
BTW, for metrics analysis please see also https://github.com/LucaCanali/sparkMeasure and https://github.com/cerndb/spark-dashboard
